### ISSUE TITLE
[Bug]: Can't install package 

### ISSUE THREAD

**Issue by ohade** [visual-layer/fastdup#199]
### What happened?

Tried to run 
```pip install fastdup```, failed to install, getting 
```
ERROR: Could not find a version that satisfies the requirement fastdup (from versions: none)
ERROR: No matching distribution found for fastdup
```

Tried to run on two setups:
1. Mac
2. EC2

Both with:
pip 23.1.2
Python 3.10.8

Mac setup:
Machine: MacBook Pro, Apple M1 Pro
OS: MacOS 13.2.1 (22D68)

EC2 setup:
Machine: m6gd.2xlarge
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"

### What did you expect to see?

Successful installation of the package

### What version of fastdup were you runnning on?

1.0

### What version of Python were you running on?

Python 3.10

### Operating System

MacOS 13.2.1, Amazon Linux 2

### Reproduction steps

1. pip install fastdup - Failed
2. pip install fastdup-1.0-cp39-cp39-macosx_11_0_arm64.whl - Failed 

### Relevant log output

```shell
On MAC
For 1:
ERROR: Could not find a version that satisfies the requirement fastdup (from versions: none)
ERROR: No matching distribution found for fastdup

For 2:
ERROR: fastdup-1.0-cp39-cp39-macosx_11_0_arm64.whl is not a supported wheel on this platform.

On EC2:
For 1:
ERROR: Could not find a version that satisfies the requirement fastdup (from versions: none)
ERROR: No matching distribution found for fastdup

For 2:
ERROR: fastdup-1.0-cp310-cp310-manylinux_2_31_x86_64.whl is not a supported wheel on this platform.
```

### Contact Details [Optional]

ohad.mailbox@gmail.com

**Comment by dbickson** [comment]
HI @ohade thanks for reaching out. We would love to help.
For max os we support only python 3.8 and 3.9 both regular python and conda.
For amazon linux 2, you need to install from our release page, since it is an older linux and our wheel fails to pass the python compatibility for old linux on pypi since we have newer dependencies. Here are the instructions: https://github.com/visual-layer/fastdup/blob/main/INSTALL.md#amazon_linux 
Please note we will release today newer version, 1.0 for Amazon linux as well so better start from mac.

**Comment by ohade** [comment]
Oh, I see, will do, thanks!

**Comment by dbickson** [comment]
Now v 1.0 is released for centos/ amazon linux as well: https://github.com/visual-layer/fastdup/releases/tag/v1.0
