### ISSUE TITLE
fastdup.run() takes a long time to complete

### ISSUE THREAD

**Issue by dnevo** [visual-layer/fastdup#23]
It would be nice if you can add a progress bar.

**Comment by dnevo** [comment]
I am using mostly Google Colab - it may be useful if you can add a progress bar for it..

**Comment by dnth** [comment]
Hello @dnevo are you still facing the same issue?

**Comment by dnevo** [comment]
I haven't used it recently...

**Comment by woctezuma** [comment]
I have run the notebook on Google Colab after reading about it in an issue about DINOv2:
- https://github.com/facebookresearch/dinov2/issues/19#issuecomment-1517650146

Apparently, it tooks 30 minutes, which is much more than advertised for `.run()` with the default arguments. 😅 

![Picture](https://i.imgur.com/PJkWln0.png)

Is it because of the use of DINOv2 instead of the default arguments?
Is there a possibility to use this Python package with a GPU if a free GPU is available on Colab?

**Comment by dbickson** [comment]
HI @woctezuma please note that the mentioned runtime are for fatsdup model, which is lightweight model and not dino v2. This colab machine is very weak just 2 cores. We recommend 32 core machine to give you x16 times speedup so you can run on this dataset in around 2 minutes. We will consider releasing gpu version in the coming days.
